from __future__ import annotations

import uuid
from typing import Any, Dict, List, Optional, TypedDict

from .config.deps import DEFAULT_MAX_RETRIES


class AIOState(TypedDict, total=False):
    """TypedDict defining the complete agent state shared across all 13 layers.

    Fields are optional (``total=False``) so that incremental mutations are
    safe.  Each layer reads the fields it needs and writes its outputs back
    into the same dict, which is then passed to the next LangGraph node.

    Key fields:
        session_id: Unique session identifier.
        trace_id: Hex trace ID used for OpenTelemetry span correlation.
        turn: Monotonically increasing turn counter.
        raw_input: Original user query string.
        intent: Classified intent (``action``, ``analysis``, ``coding``, ``general``).
        context_window: Ordered list of messages in the current context.
        context_budget: Remaining token budget after sculpting.
        attention_map: BAPO attention weights per downstream layer.
        working_memory: Episodic entries retrieved for the current turn.
        long_term_memory: Consolidated entries promoted from episodic storage.
        memory_confidence: Top similarity score from the retrieval phase.
        plan: Flat plan string produced by the planning layer.
        hierarchical_plan: Nested goal tree from HiPlan.
        lookahead_result: FLARE trajectory scores and risk assessment.
        fact_augmented_plan: Plan enriched with verified memory facts (LWM).
        pitfall_analysis: PPA guardrails and safety flags.
        spiral_tree: MCTS search tree from SPIRAL.
        mars_reflection: Self-critique string from MARS.
        maci_meta_plan: Name of the planner selected by MACI.
        vmao_dag: Executable DAG nodes from VMAO decomposition.
        curiosity_score: Intrinsic reward computed by Layer 4.
        novelty_map: Hash-to-novelty mapping for visited states.
        information_gaps: Questions generated by active seeking.
        verification_result: Ensemble critique, formal checks, and debug hypotheses.
        tool_necessity_score: G-STEP necessity score (Layer 6).
        tool_policy_channels: HDPO accuracy / efficiency scores.
        tool_prompt_optimization: JTPRO refinement iterations.
        sandbox_result: Docker sandbox metadata (Layer 7).
        tool_analytics: Usage statistics and deprecation flags.
        execution_result: Raw tool output (stdout, stderr, exit code).
        failure_state: One of ``HEALTHY``, ``DEGRADED``, ``RECOVERING``, ``FAILED``.
        failure_count: Cumulative failures in the current session.
        retry_budget: Remaining retries before escalation.
        safety_violations: List of NeuroShield interceptions.
        output: Final agent response string.
        error: Human-readable error message if the pipeline failed.
        metrics: Free-form diagnostic bag (latency, custom counters, etc.).
        self_evolution_report: Performance trend summary (Layer 9).
        performance_snapshot: Latest turn-level performance record.
        suggested_config_delta: Safe config changes proposed by self-evolution.
        coordination_plan: Subtask decomposition (Layer 10).
        agent_outputs: Per-agent results from multi-agent dispatch.
        consensus_score: Aggregated confidence minus variance.
        _ma_needed_agents: Internal queue of agents for LangGraph backend.
        _ma_subtasks: Internal subtask list for LangGraph backend.
        audit_trail: Per-turn governance audit entries (Layer 11).
        governance_result: Voting outcome and majority score.
        compliance_violations: Constitutional or procedural breaches.
        immune_status: ``HEALTHY``, ``WATCH``, or ``ALERT`` (Layer 12).
        anomaly_score: Heuristic anomaly score [0, 1].
        quarantined_ids: IDs of memory entries moved to quarantine.
        healing_actions: Auto-heal steps applied by the immune layer.
        threat_patterns_detected: Rolling threat pattern database snapshot.
        learned_anomaly_score: Z-score based anomaly from immune learning.
        mcp_discovered_tools: Tools auto-registered via MCP discovery.
        mcp_execution_metadata: Latency and server info for MCP calls.
        mcp_errors: JSON-RPC or transport errors from MCP client.
    """

    session_id: str
    trace_id: str
    turn: int
    raw_input: str
    intent: Optional[str]
    context_window: List[Dict[str, Any]]
    context_budget: int
    attention_map: Dict[str, float]
    working_memory: List[Dict[str, Any]]
    long_term_memory: List[Dict[str, Any]]
    memory_confidence: float
    plan: Optional[str]
    hierarchical_plan: Optional[Dict[str, Any]]
    lookahead_result: Optional[Dict[str, Any]]
    fact_augmented_plan: Optional[str]
    pitfall_analysis: Optional[Dict[str, Any]]
    spiral_tree: Optional[Dict[str, Any]]
    mars_reflection: Optional[str]
    maci_meta_plan: Optional[str]
    vmao_dag: Optional[List[Dict[str, Any]]]
    curiosity_score: float
    novelty_map: Dict[str, float]
    information_gaps: List[str]
    verification_result: Dict[str, Any]
    tool_necessity_score: float
    tool_policy_channels: Dict[str, Any]
    tool_prompt_optimization: Dict[str, Any]
    sandbox_result: Optional[Dict[str, Any]]
    tool_analytics: Dict[str, Any]
    execution_result: Dict[str, Any]
    failure_state: str
    failure_count: int
    retry_budget: int
    safety_violations: List[Dict[str, Any]]
    output: Optional[str]
    error: Optional[str]
    metrics: Dict[str, Any]
    # Layer 9 — Self-Evolution
    self_evolution_report: Optional[Dict[str, Any]]
    performance_snapshot: Optional[Dict[str, Any]]
    suggested_config_delta: Optional[List[Dict[str, Any]]]
    # Layer 10 — Multi-Agent Coordination
    coordination_plan: Optional[Dict[str, Any]]
    agent_outputs: Optional[Dict[str, Any]]
    consensus_score: Optional[float]
    # Internal routing fields for LangGraph multi-agent backend
    _ma_needed_agents: Optional[List[str]]
    _ma_subtasks: Optional[List[Dict[str, Any]]]
    # Layer 11 — Safety & Governance
    audit_trail: Optional[List[Dict[str, Any]]]
    governance_result: Optional[Dict[str, Any]]
    compliance_violations: Optional[List[Dict[str, Any]]]
    # Layer 12 — Cognitive Immune System
    immune_status: Optional[str]
    anomaly_score: Optional[float]
    quarantined_ids: Optional[List[str]]
    healing_actions: Optional[List[Dict[str, Any]]]
    threat_patterns_detected: Optional[List[Dict[str, Any]]]
    learned_anomaly_score: Optional[float]
    # MCP (Priority 5)
    mcp_discovered_tools: Optional[List[str]]
    mcp_execution_metadata: Optional[Dict[str, Any]]
    mcp_errors: Optional[List[str]]
    # Neuro-Symbolic Mandate
    neuro_symbolic_plan: Optional[Dict[str, Any]]
    neuro_symbolic_inference: Optional[Dict[str, Any]]
    neuro_symbolic_grounding: Optional[List[Dict[str, Any]]]
    neuro_symbolic_verdict: Optional[Dict[str, Any]]
    neuro_symbolic_confidence: Optional[float]
    # Deep Neuro-Symbolic Integration (Priority 9)
    symbolic_constraints: Optional[Dict[str, Any]]
    symbolic_solver_result: Optional[Dict[str, Any]]
    symbolic_plan_validated: Optional[bool]
    symbolic_verdict: Optional[Dict[str, Any]]


def make_initial_state(raw_input: str = "", session_id: Optional[str] = None) -> AIOState:
    """Return a fresh :class:`AIOState` dict with sensible defaults.

    Args:
        raw_input: The user query that starts the session.
        session_id: Optional stable identifier; a random UUID is generated if omitted.

    Returns:
        An :class:`AIOState` dict ready to be passed to ``graph.invoke()``.

    Example::

        state = make_initial_state("echo hello", session_id="demo-001")
        result = graph.invoke(state)
    """
    sid = session_id or str(uuid.uuid4())
    trace_id = str(uuid.uuid4()).replace("-", "")
    return {
        "session_id": sid,
        "trace_id": trace_id,
        "turn": 0,
        "raw_input": raw_input,
        "intent": None,
        "context_window": [],
        "context_budget": 4096,
        "attention_map": {},
        "working_memory": [],
        "long_term_memory": [],
        "memory_confidence": 0.0,
        "plan": None,
        "hierarchical_plan": None,
        "lookahead_result": None,
        "fact_augmented_plan": None,
        "pitfall_analysis": None,
        "spiral_tree": None,
        "mars_reflection": None,
        "maci_meta_plan": None,
        "vmao_dag": None,
        "curiosity_score": 0.0,
        "novelty_map": {},
        "information_gaps": [],
        "verification_result": {},
        "tool_necessity_score": 0.0,
        "tool_policy_channels": {},
        "tool_prompt_optimization": {},
        "sandbox_result": None,
        "tool_analytics": {},
        "execution_result": {},
        "failure_state": "HEALTHY",
        "failure_count": 0,
        "retry_budget": DEFAULT_MAX_RETRIES,
        "safety_violations": [],
        "output": None,
        "error": None,
        "metrics": {},
        "self_evolution_report": None,
        "performance_snapshot": None,
        "suggested_config_delta": None,
        "coordination_plan": None,
        "agent_outputs": None,
        "consensus_score": None,
        "_ma_needed_agents": None,
        "_ma_subtasks": None,
        "audit_trail": None,
        "governance_result": None,
        "compliance_violations": None,
        "immune_status": None,
        "anomaly_score": None,
        "quarantined_ids": None,
        "healing_actions": None,
        "threat_patterns_detected": None,
        "learned_anomaly_score": None,
        "mcp_discovered_tools": None,
        "mcp_execution_metadata": None,
        "mcp_errors": None,
        "neuro_symbolic_plan": None,
        "neuro_symbolic_inference": None,
        "neuro_symbolic_grounding": None,
        "neuro_symbolic_verdict": None,
        "neuro_symbolic_confidence": None,
        "symbolic_constraints": None,
        "symbolic_solver_result": None,
        "symbolic_plan_validated": None,
        "symbolic_verdict": None,
        }
